#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Check for commit message formatting
echo "🔎 Checking commit message formatting...";
npx --no -- commitlint --edit "$1" ||
(
  echo "❌ Commit message formatting errors detected. Please fix and commit again.";
  false;
)

echo "✅ Commit message formatting check passed. Committing...";
